// Behaviour tests for states the route matrix cannot reach. Screenshots → qa/screenshots/states/
import fs from 'fs';
import { launch, newCtx, watch, signIn, settle, URL0 } from './lib.mjs';
const OUT = new URL('./screenshots/states', import.meta.url).pathname; fs.mkdirSync(OUT, { recursive: true });
const results = []; let cur = '';
const ok = (name, cond, info = '') => { results.push({ name: cur + ' · ' + name, pass: !!cond, info: String(info).slice(0, 200) }); process.stdout.write(cond ? '.' : 'F'); };
const b = await launch();
async function block(fn) { try { await fn(); } catch (e) { ok('step threw', false, e.message.split('\n')[0]); } }
async function fresh(opts = {}) { const ctx = await newCtx(b, opts); const p = await ctx.newPage(); const errs = []; watch(p, errs); await p.addInitScript(() => { window.__long = []; try { new PerformanceObserver((l) => { for (const e of l.getEntries()) window.__long.push(Math.round(e.duration)); }).observe({ type: 'longtask', buffered: true }); } catch {} }); return { ctx, p, errs }; }
const shot = (p, n) => p.screenshot({ path: `${OUT}/${n}.jpg`, type: 'jpeg', quality: 60 });
const ev = (p, fn, arg) => p.evaluate(fn, arg);

await block(async () => { cur = 'consent'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en', 'aysel@kerimova-servis.az');
  ok('invited user lands on consent', (await ev(p, () => location.hash)) === '#/consent');
  const cont = p.locator('.consent-foot .btn-primary');
  ok('continue disabled initially', await cont.isDisabled());
  ok('required boxes unticked', !(await p.isChecked('#cg-tos')) && !(await p.isChecked('#cg-pd')));
  await p.check('#cg-fc'); ok('optional only keeps continue disabled', await cont.isDisabled());
  await p.check('#cg-tos'); ok('one required still disabled', await cont.isDisabled());
  await p.check('#cg-pd'); ok('both required enables continue', !(await cont.isDisabled()));
  await p.click('.c-block .link-btn >> nth=0'); await p.waitForSelector('.drawer'); await p.waitForTimeout(400);
  const dtxt = await p.textContent('.drawer'); ok('drawer shows version/effective/language', /Version 2\.4/.test(dtxt) && /Effective/.test(dtxt) && /Language: English/.test(dtxt), dtxt.slice(0, 120));
  await shot(p, 'consent-drawer'); await p.keyboard.press('Escape'); await p.waitForTimeout(200);
  ok('escape closes drawer, focus returns', !(await p.$('.drawer')) && (await ev(p, () => document.activeElement.classList.contains('link-btn'))));
  await cont.click(); await p.waitForFunction(() => location.hash === '#/overview', null, { timeout: 10000 });
  const acc = await ev(p, () => api.get('/v1/me/acceptances'));
  const tos = acc.items.find((r) => r.doc_key === 'tos');
  ok('acceptance record fields', tos && /^[0-9a-f]{64}$/.test(tos.sha256) && tos.version === '2.4' && tos.language === 'en' && tos.method === 'gate' && tos.ip && tos.user_agent && tos.org_id && tos.user_id && /Z$/.test(tos.accepted_at), JSON.stringify(tos));
  ok('record is immutable', await ev(p, () => { const r = mockServer.db().ledger.at(-1); try { r.sha256 = 'x'; } catch { return true; } return r.sha256 !== 'x'; }));
  ok('optional consent recorded', acc.items.some((r) => r.doc_key === 'consent:radio_stats' && r.action === 'grant') && acc.items.some((r) => r.doc_key === 'consent:product_news' && r.action === 'withdraw'));
  const hashOk = await ev(p, async () => { const r = (await api.get('/v1/me/acceptances')).items.find((x) => x.doc_key === 'tos'); return r.sha256 === await sha256Hex(LEGAL.rendered('tos', '2.4', 'en')); });
  ok('sha256 matches rendered text', hashOk);
  ok('contractor sees no coordinates', await (async () => { await ev(p, () => location.hash = '#/nodes/nd_cyr6wckwnn?tab=set'); await settle(p); return /Hidden for your role/.test(await p.textContent('main')); })());
  await ev(p, () => location.hash = '#/activity'); await settle(p); ok('contractor gets 403 on activity', /don’t have access/.test(await p.textContent('main'))); await shot(p, '403-contractor');
  await ev(p, () => location.hash = '#/settings/members'); await settle(p); ok('contractor members → 403', /don’t have access/.test(await p.textContent('main')));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'errors'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en');
  for (const [code, re, name] of [[500, /Request ID: req_/, 'error-500'], [404, /can’t find this/, 'error-404'], [403, /don’t have access/, 'error-403'], [429, /Trying again in \d+ s/, 'error-429']]) {
    await ev(p, (c) => { mockServer.debug.next = c; mockServer.debug.sticky = c !== 429; location.hash = '#/gateways?x=' + c; }, code); await settle(p, 800);
    ok(`forced ${code} state`, re.test(await p.textContent('main')), (await p.textContent('main')).slice(0, 150)); await shot(p, name);
    await ev(p, () => { mockServer.debug.sticky = false; if (mockServer.debug.next !== 429) mockServer.debug.next = null; });
  }
  await p.waitForTimeout(13000); ok('429 auto-retries after Retry-After', /GW-01/.test(await p.textContent('main')));
  await ev(p, () => { location.hash = '#/alerts'; }); await settle(p);
  await ev(p, () => { mockServer.debug.next = 401; store.emit('refresh'); }); await p.waitForSelector('.modal', { timeout: 8000 }).catch(() => {});
  ok('401 opens re-auth modal', /session has expired/.test(await p.textContent('body'))); await shot(p, 'session-expired');
  ok('page kept behind modal', !!(await p.$('.alerts-split')));
  await p.click('.modal .btn-primary'); await p.waitForTimeout(1500); ok('re-auth resumes', !(await p.$('.modal')) && !!(await p.$('.alerts-split')));
  await ev(p, () => { mockServer.setMaint({ from: clock.now(), until: clock.now() + 1800e3, now: true }); location.hash = '#/overview?m=1'; }); await settle(p);
  ok('maintenance state', /planned maintenance/.test(await p.textContent('main'))); await shot(p, 'maintenance-now');
  await ev(p, () => { mockServer.setMaint({ from: clock.now() + 4 * 864e5, until: clock.now() + 4 * 864e5 + 1800e3, now: false }); app.loadMe().then(() => app.render()); }); await settle(p);
  ok('maintenance banner', /Planned maintenance on/.test(await p.textContent('.banners'))); await shot(p, 'maintenance-banner');
  await ev(p, () => { mockServer.setMaint(null); mockServer.setFleet('empty'); api.cache.clear(); location.hash = '#/overview?e=1'; }); await settle(p);
  ok('empty state', /No nodes yet/.test(await p.textContent('main'))); await shot(p, 'empty');
  await ev(p, () => { mockServer.setFleet('normal'); location.hash = '#/nodes/' + mockServer.FOREIGN.node; }); await settle(p);
  const foreign = await p.textContent('main');
  await ev(p, () => { location.hash = '#/nodes/nd_unknown1234'; }); await settle(p);
  const unknown = await p.textContent('main');
  ok('foreign and unknown IDs give the same 404', foreign === unknown && /can’t find/.test(unknown));
  const r1 = await ev(p, async () => { try { await api.get('/v1/nodes/' + mockServer.FOREIGN.node); } catch (e) { return [e.status, JSON.stringify(e.body)]; } });
  const r2 = await ev(p, async () => { try { await api.get('/v1/nodes/nd_zzzzzzzzzz'); } catch (e) { return [e.status, JSON.stringify(e.body)]; } });
  ok('API 404 bodies identical', JSON.stringify(r1) === JSON.stringify(r2), JSON.stringify([r1, r2]));
  ok('raw packets capped at 24 h', await ev(p, async () => { try { await api.get('/v1/nodes/nd_cyr6wckwnn/packets', { from: clock.now() - 3 * 864e5, to: clock.now() }); return false; } catch (e) { return e.status === 422; } }));
  ok('series capped at 2,000 points', await ev(p, async () => { const r = await api.get('/v1/nodes/nd_cyr6wckwnn/series', { metric: 'loss', from: clock.now() - 7 * 864e5, to: clock.now(), step: '5m' }); return r.series[0].points.length <= 2000 && r.step !== '5m'; }));
  ok('ids are opaque', await ev(p, async () => { const r = await api.get('/v1/nodes', { limit: 5 }); return r.items.every((x) => /^nd_[a-z2-9]{10}$/.test(x.id)); }));
  ok('keyset cursor paging', await ev(p, async () => { const a = await api.get('/v1/nodes', { limit: 20 }); const b2 = await api.get('/v1/nodes', { limit: 20, cursor: a.next_cursor }); return a.items.length === 20 && b2.items[0].id !== a.items[19].id && b2.start === 20; }));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'offline+realtime'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en'); await ev(p, () => location.hash = '#/alerts'); await settle(p, 800);
  const seq0 = await ev(p, () => realtime.lastSeq);
  await p.waitForTimeout(6000); ok('SSE batches arrive every 5 s', (await ev(p, () => realtime.lastSeq)) > seq0);
  await ev(p, () => { mockServer.debug.net = 'offline'; store.set('online', false); realtime.drop(); app.renderBanners(); app.updateLive(); });
  await p.waitForTimeout(300);
  ok('offline banner with snapshot time', /No internet connection\. Showing data from \d\d:\d\d/.test(await p.textContent('.banners')));
  ok('status shows paused', /Paused/.test(await p.textContent('.live-btn')));
  await p.click('.al-item >> nth=0'); await p.waitForTimeout(300);
  const ackBtn = p.locator('.al-detail .btn-primary'); if (await ackBtn.count()) await ackBtn.click(); await p.waitForTimeout(700);
  ok('queued action marked pending', /Pending/.test(await p.textContent('.al-detail')) || /Pending/.test(await p.textContent('.toasts')));
  await shot(p, 'offline-queued');
  const lastSeq = await ev(p, () => realtime.lastSeq);
  await ev(p, () => { mockServer.debug.net = 'normal'; store.set('online', true); api.flush(); realtime.resume(); app.renderBanners(); });
  await p.waitForTimeout(7000);
  ok('queued change sent on reconnect', /queued change/.test(await p.textContent('body')) || (await ev(p, () => store.get('queue').length)) === 0);
  ok('stream resumed from last sequence', (await ev(p, () => realtime.lastSeq)) > lastSeq && (await ev(p, () => realtime.state)) === 'live');
  await ev(p, () => realtime.drop()); await p.waitForTimeout(100);
  ok('reconnecting state shown', /Reconnecting/.test(await p.textContent('.live-btn'))); await shot(p, 'reconnecting');
  await p.waitForTimeout(3500); ok('reconnects with backoff', (await ev(p, () => realtime.state)) === 'live');
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'legal-change'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en');
  await ev(p, async () => { mockServer.announceTerms(); await app.loadMe(); app.shell = null; app.render(); }); await settle(p);
  ok('terms banner 30 days before', /New Terms of Service apply from/.test(await p.textContent('.banners'))); await shot(p, 'terms-banner');
  await ev(p, () => location.hash = '#/legal/tos?version=3.0'); await settle(p);
  ok('review page', /What changes, in plain words/.test(await p.textContent('main'))); await shot(p, 'terms-review');
  await ev(p, () => mockServer.effectiveTerms()); await p.reload(); await p.waitForTimeout(1500);
  ok('blocking screen after effective date', /now apply/.test(await p.textContent('body')) && !(await p.$('.sidebar'))); await shot(p, 'terms-blocking');
  ok('blocking has Accept · Download · Decline', /Accept/.test(await p.textContent('main')) && /Download my data/.test(await p.textContent('main')) && /Decline/.test(await p.textContent('main')));
  await p.click('main .btn-primary'); await p.waitForTimeout(1500);
  ok('accept unblocks', (await ev(p, () => location.hash)) === '#/overview' && !!(await p.$('.sidebar')));
  const recs = await ev(p, () => api.get('/v1/me/acceptances'));
  ok('3.0 acceptance recorded (method block)', recs.items.some((r) => r.doc_key === 'tos' && r.version === '3.0' && r.method === 'block'));
  await ev(p, () => location.hash = '#/legal/tos'); await settle(p);
  await ev(p, () => location.hash = '#/settings/privacy'); await settle(p);
  const priv = await p.textContent('main'); ok('history in Privacy & data', /3\.0/.test(priv) && /SHA-256/.test(priv)); await shot(p, 'privacy-history');
  await p.click('#set-content .switch >> nth=1'); await p.waitForTimeout(800);
  const recs2 = await ev(p, () => api.get('/v1/me/acceptances'));
  ok('toggle consent recorded with version', recs2.items[0].doc_key === 'consent:product_news' && recs2.items[0].version === '1');
  await ev(p, () => location.hash = '#/activity'); await settle(p);
  ok('acceptances in Activity', /accepted Terms of Service 3\.0/.test(await p.textContent('main')));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'admin-flows'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en');
  await ev(p, () => location.hash = '#/settings/api-keys'); await settle(p);
  await p.click('text=Create key'); await p.fill('.modal input', 'Irrigation controller'); await p.click('.modal .btn-primary'); await p.waitForSelector('.code-box', { timeout: 5000 });
  const secret = await p.textContent('.code-box code'); ok('secret shown once', /^agl_read_[A-Za-z0-9]{34}$/.test(secret), secret);
  await shot(p, 'api-key-secret');
  await p.click('.modal .btn-primary'); await p.waitForTimeout(900);
  ok('after Done only masked prefix', !(await p.content()).includes(secret) && /agl_read_•••• /.test(await p.textContent('main')));
  ok('server stores only a hash', await ev(p, (s0) => !JSON.stringify(mockServer.db().keys).includes(s0), secret));
  await ev(p, () => location.hash = '#/settings/support'); await settle(p);
  await p.fill('#set-content input.mono', 'RS-20'); await p.click('text=Allow access'); await p.waitForTimeout(300);
  ok('support: validation', /RS-20418/.test(await p.textContent('#set-content .err')));
  await p.fill('#set-content input.mono', 'RS-20418'); await p.click('text=Allow access'); await p.waitForTimeout(1200);
  ok('support: countdown banner', /Ruta support can view your account until/.test(await p.textContent('.banners')) && /\d+:\d\d/.test(await p.textContent('.banners [data-countdown]')));
  await shot(p, 'support-access');
  await p.click('.banners .btn'); await p.waitForTimeout(1000); ok('support: revoke', !/Ruta support can view/.test(await p.textContent('.banners')));
  await ev(p, () => location.hash = '#/alerts'); await settle(p);
  await p.click('text=Alert rules'); await p.waitForSelector('.drawer'); await p.waitForTimeout(700);
  await p.click('.drawer button:has-text("Edit") >> nth=1'); await p.waitForTimeout(400);
  const inputs = p.locator('.drawer >> nth=-1').locator('input.input');
  await inputs.nth(0).fill('0'); await inputs.nth(2).fill('5');
  await p.click('.drawer >> nth=-1 >> text=Save rule'); await p.waitForTimeout(300);
  const etext = await p.locator('.drawer >> nth=-1').textContent();
  ok('rule validation messages', /Enter a number from 1 to 120/.test(etext) && /Must be lower than the alert level/.test(etext) && /Fix 2 fields/.test(etext), etext.slice(0, 200));
  await shot(p, 'rule-validation');
  await inputs.nth(0).fill('15'); await inputs.nth(2).fill('1.5');
  await p.click('.drawer >> nth=-1 >> text=Send test'); await p.waitForTimeout(700);
  ok('send test toast', /Test alert sent to/.test(await p.textContent('.toasts')));
  await p.click('.drawer >> nth=-1 >> text=Save rule'); await p.waitForTimeout(900);
  ok('rule saved', /saved/.test(await p.textContent('.toasts')));
  await p.keyboard.press('Escape'); await p.waitForTimeout(300);
  await p.click('.al-item >> nth=0'); await p.click('.al-detail >> text=Snooze'); await p.waitForSelector('.modal');
  await p.click('.modal .btn-primary'); await p.waitForTimeout(200); ok('snooze requires reason', /Choose a reason/.test(await p.textContent('.modal')));
  await p.check('.modal input[value=known]'); await p.check('.modal input[value="4h"]'); await p.click('.modal .btn-primary'); await p.waitForTimeout(900);
  ok('snooze toast with undo', /snoozed until/.test(await p.textContent('.toasts')) && /Undo/.test(await p.textContent('.toasts')));
  await ev(p, () => location.hash = '#/data'); await settle(p);
  await p.click('text=Create export'); await p.waitForTimeout(3500);
  ok('export appears and becomes ready', /Ready/.test(await p.textContent('main')));
  ok('coordinates off by default', !(await ev(p, () => document.querySelector('main .switch').getAttribute('aria-checked') === 'true')));
  await ev(p, () => location.hash = '#/activity'); await settle(p); ok('export in activity', /exported 7 days of/.test(await p.textContent('main')));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'keyboard+perf'; const { ctx, p, errs } = await fresh();
  await signIn(p, 'en'); await settle(p);
  await p.keyboard.press('Control+k'); await p.waitForSelector('.palette');
  await p.keyboard.type('N-14'); await p.waitForTimeout(200); await shot(p, 'palette');
  await p.keyboard.press('Enter'); await p.waitForTimeout(1500);
  ok('palette opens node', /nodes\/nd_cyr6wckwnn/.test(await ev(p, () => location.hash)));
  await p.keyboard.press('Control+k'); await p.waitForSelector('.palette'); await p.keyboard.type('api'); await p.keyboard.press('ArrowDown'); await p.keyboard.press('Escape'); await p.waitForTimeout(200);
  ok('palette escape closes', !(await p.$('.palette')));
  await p.keyboard.press('Control+Shift+D'); await p.waitForSelector('.dbg'); await shot(p, 'debug-panel'); ok('debug panel opens', true); await p.keyboard.press('Escape');
  await ev(p, () => { mockServer.setFleet('stress'); api.cache.clear(); location.hash = '#/nodes'; }); await settle(p, 1500);
  ok('stress footer 10,000', /of 10,000/.test(await p.textContent('.vt-foot')), await p.textContent('.vt-foot'));
  ok('only visible rows rendered', (await ev(p, () => document.querySelectorAll('.vt-row').length)) < 60);
  await ev(p, () => window.__long = []);
  for (let i = 0; i < 30; i++) { await ev(p, (y) => { document.querySelector('.vt-scroll').scrollTop = y; }, i * 900); await p.waitForTimeout(60); }
  await p.waitForTimeout(2500);
  const longScroll = await ev(p, () => window.__long.slice());
  ok('no long tasks (>50 ms) while scrolling 10k rows', longScroll.every((d) => d <= 50), JSON.stringify(longScroll));
  await ev(p, () => { document.querySelector('.vt-scroll').scrollTop = 1e9; }); await p.waitForTimeout(9000);
  ok('keyset paging reaches the end', /10,000–10,000 of 10,000|9,99\d–10,000 of 10,000/.test(await p.textContent('.vt-foot')) || (await ev(p, () => document.querySelector('.vt-row:not([aria-busy]) .id')?.textContent || '')).startsWith('N-'), await p.textContent('.vt-foot'));
  await shot(p, 'nodes-10000');
  await ev(p, () => { mockServer.setFleet('normal'); location.hash = '#/nodes?status=attention&sort=-loss'; }); await settle(p, 1000);
  ok('filters and sort from URL', (await p.locator('.vt-row').count()) === 3 && /aria-sort/.test(await p.innerHTML('.vt-head')));
  await p.locator('.vt-row [role=gridcell] >> nth=0').focus(); await p.keyboard.press('ArrowDown'); await p.keyboard.press('ArrowRight');
  ok('grid roving tabindex', await ev(p, () => document.activeElement.getAttribute('aria-colindex') === '2' && document.activeElement.closest('[aria-rowindex]').getAttribute('aria-rowindex') === '3'));
  await ev(p, () => window.__long = []);
  for (const r of ['#/overview', '#/alerts', '#/forecast', '#/map', '#/nodes/nd_cyr6wckwnn', '#/gateways', '#/activity']) { await ev(p, (x) => location.hash = x, r); await settle(p, 400); }
  const longNav = await ev(p, () => window.__long.slice());
  ok('navigation long tasks', longNav.every((d) => d <= 50), JSON.stringify(longNav));
  const t0 = Date.now(); await p.reload(); await p.waitForSelector('main h2.headline', { timeout: 15000 }).catch(() => {});
  const nav = await ev(p, () => { const e = performance.getEntriesByType('navigation')[0]; const fcp = performance.getEntriesByName('first-contentful-paint')[0]; return { dcl: Math.round(e.domContentLoadedEventEnd), fcp: fcp ? Math.round(fcp.startTime) : null, now: Math.round(performance.now()) }; });
  ok('first render under 1 s', nav.fcp !== null && nav.fcp < 1000, JSON.stringify(nav) + ' wall ' + (Date.now() - t0));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'storage-blocked+pseudo'; const ctx = await newCtx(b); await ctx.addInitScript(() => { const thrower = () => { throw new DOMException('blocked', 'SecurityError'); }; Storage.prototype.setItem = thrower; Storage.prototype.getItem = thrower; Storage.prototype.removeItem = thrower; });
  const p = await ctx.newPage(); const errs = []; watch(p, errs);
  await signIn(p, 'en'); await settle(p); ok('works with storage blocked', /nodes are working normally/.test(await p.textContent('main')));
  await ev(p, () => location.hash = '#/settings/general'); await settle(p); ok('storage notice', /blocks local storage/.test(await p.textContent('main')));
  await p.goto(URL0 + '?lang=xx#/overview'); await p.waitForTimeout(1500);
  ok('pseudo-locale renders', /⟦/.test(await p.textContent('body'))); await shot(p, 'pseudo-locale');
  ok('html lang set', (await ev(p, () => document.documentElement.lang)) === 'en-XA');
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await block(async () => { cur = 'mobile-dark-states'; const { ctx, p, errs } = await fresh({ w: 390, h: 844, scheme: 'dark' });
  await signIn(p, 'az'); await settle(p); await shot(p, 'mobile-dark-az-overview');
  await ev(p, () => location.hash = '#/alerts?id=' + mockServer.db().alerts[0].id); await settle(p); await shot(p, 'mobile-dark-az-alert');
  ok('az suffix harmony', /52 qovşaqdan 46-sı normal işləyir|46-sı/.test(await (async () => { await ev(p, () => location.hash = '#/overview'); await settle(p); return p.textContent('main'); })()));
  ok('az updated text', /Bakı vaxtı ilə \d\d:\d\d-(də|da) yeniləndi/.test(await p.textContent('.mstatus')), await p.textContent('.mstatus'));
  ok('no console errors', !errs.length, errs.join(' | ')); await ctx.close(); });

await b.close();
fs.writeFileSync(new URL('./flows.json', import.meta.url).pathname, JSON.stringify(results, null, 1));
const fails = results.filter((r) => !r.pass);
console.log(`\n${results.length - fails.length}/${results.length} checks passed`);
for (const f of fails) console.log('FAIL', f.name, '::', f.info);
